# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
communes = Commune.create([
                              { name: "Cerrillos"},
                              { name: "Cerro Navia"},
                              { name: "Conchalí"},
                              { name: "El Bosque"},
                              { name: "Estación Central"},
                              { name: "Huechuraba"},
                              { name: "Independencia"},
                              { name: "La Cisterna"},
                              { name: "La Florida"},
                              { name: "La Granja"},
                              { name: "La Pintana"},
                              { name: "La Reina"},
                              { name: "Las Condes"},
                              { name: "Lo Barnechea"},
                              { name: "Lo Espejo"},
                              { name: "Lo Prado"},
                              { name: "Macul"},
                              { name: "Maipú"},
                              { name: "Ñuñoa"},
                              { name: "Pedro Aguirre Cerda"},
                              { name: "Peñalolén"},
                              { name: "Providencia"},
                              { name: "Pudahuel"},
                              { name: "Quilicura"},
                              { name: "Quinta Normal"},
                              { name: "Recoleta"},
                              { name: "Renca"},
                              { name: "Santiago"},
                              { name: "San Joaquín"},
                              { name: "San Miguel"},
                              { name: "San Ramón"},
                              { name: "Vitacura"},
                              { name: "Puente Alto"},
                              { name: "Pirque"},
                              { name: "San José de Maipo"},
                              { name: "Colina"},
                              { name: "Lampa"},
                              { name: "Tiltil"},
                              { name: "San Bernardo"},
                              { name: "Buin"},
                              { name: "Calera de Tango"},
                              { name: "Paine"},
                              { name: "Melipilla"},
                              { name: "Alhué"},
                              { name: "Curacaví"},
                              { name: "María Pinto"},
                              { name: "San Pedro"},
                              { name: "Talagante"},
                              { name: "El Monte"},
                              { name: "Isla de Maipo"},
                              { name: "Padre Hurtado"},
                              { name: "Peñaflor"}
                          ])
loads = Load.create([{type_load: "general"}, {type_load: "freezer"}])